/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaProject;


import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import javax.swing.Timer;

/**
 *
 * @author dharm
 */
public class ktNhayBen extends javax.swing.JFrame {
    private String textColor;
    private String text;
    Timer time;
    private int scoreCount = 0, timeCount, levelCount;
    private int rdColor,rdText;
    private String[] colors = {"white", "black","gray","blue", "red", "cyan","pink","orange","yellow","green"};
    private  ArrayList<Color> colorList = new ArrayList<Color>(){
        {
            add(Color.white);
            add(Color.black); 
            add(Color.gray); 
            add(Color.blue); 
            add(Color.red); 
            add(Color.cyan); 
            add(Color.pink);
            add(Color.orange);
            add(Color.yellow);
            add(Color.green); 
        }
    };
    

    /**
     * Creates new form ktNhayBen
     */
    public ktNhayBen() {
        initComponents();
    }
    
    public void loadText()
    {
        Random rd = new Random();
        rdColor = rd.nextInt(9);
        rdText = rd.nextInt(9);
        mainLabel.setForeground(colorList.get(rdColor));
        mainLabel.setText(colors[rdText].toUpperCase());
        levelLabel.setText("Level: " + levelCount);
        scoreLabel.setText("Score: " + scoreCount);
        boolean rdBtn = rd.nextBoolean(); // re.nextInt(1) always return 0. I dunno what the fuck is going on.
        System.out.println(rdBtn);
        if(rdBtn)
        {
            if(rdColor==rdText) 
            {
                oneBtn.setText(colors[rdColor].toUpperCase());
                twoBtn.setText(colors[rd.nextInt(9)].toUpperCase());
            } 
            else
            {
            oneBtn.setText(colors[rdColor].toUpperCase());
            twoBtn.setText(colors[rdText].toUpperCase());
            }
        }
        else
        {
            if(rdColor==rdText) 
            {
                oneBtn.setText(colors[rdColor].toUpperCase());
                twoBtn.setText(colors[rd.nextInt(9)].toUpperCase());
            } else
            {
            oneBtn.setText(colors[rdText].toUpperCase());
            twoBtn.setText(colors[rdColor].toUpperCase());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new java.awt.Label();
        desLabel = new java.awt.Label();
        oneBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JButton();
        startBtn = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        levelLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        mainLabel.setAlignment(java.awt.Label.CENTER);
        mainLabel.setFont(new java.awt.Font("Nexa XBold", 1, 48)); // NOI18N
        mainLabel.setText("BlindColor");

        desLabel.setAlignment(java.awt.Label.CENTER);
        desLabel.setFont(new java.awt.Font("Nexa Bold", 0, 14)); // NOI18N
        desLabel.setText("Choose the color of text, not the text.");

        oneBtn.setText("Color1");
        oneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtnActionPerformed(evt);
            }
        });

        twoBtn.setText("Color2");
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });

        startBtn.setText("Start");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        levelLabel.setFont(new java.awt.Font("Nexa Bold", 1, 24)); // NOI18N
        levelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        levelLabel.setText("Level");

        scoreLabel.setFont(new java.awt.Font("Nexa Bold", 1, 24)); // NOI18N
        scoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel.setText("Score");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(desLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(twoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {oneBtn, twoBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(levelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(startBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {oneBtn, twoBtn});

        mainLabel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()== startBtn)
        {
            timeCount = 100;
            if(startBtn.getText().equals("Play again?")) 
            {
                scoreCount = 0;
                levelCount =0;
                loadText();
                time = new Timer(55 - levelCount*5, new loadTime());
                time.start();
                return;
                
            }
            if(levelCount<10) 
            {
                levelCount++;
                startBtn.setText("Level Up?");
            }
            else startBtn.setText("Final level");
            loadText();
            time = new Timer(55 - levelCount*5, new loadTime());
            time.start();
        }
    }//GEN-LAST:event_startBtnActionPerformed

    private void oneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtnActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==oneBtn)
        {
            System.out.println(oneBtn.getText().toLowerCase()+" "+colors[rdColor].toLowerCase());
            if(oneBtn.getText().toLowerCase().equals(colors[rdColor].toLowerCase()))
            {
                loadText();
                scoreCount += levelCount;
                if(levelCount<10&&(scoreCount%50==0)) 
                    {
                        levelCount++;
                    }
                timeCount =100;
                time.start();
            }
            else {
                time.stop();
                mainLabel.setText("GAME OVER");
                mainLabel.setForeground(Color.red);
                desLabel.setText("Wrong Answer.");
                oneBtn.setText("Color one");
                twoBtn.setText("Color two");
                startBtn.setText("Play again?");
 
            }
        }
    }//GEN-LAST:event_oneBtnActionPerformed

    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==twoBtn)
            {
                System.out.println(twoBtn.getText().toLowerCase()+" "+colors[rdColor].toLowerCase());
                if(twoBtn.getText().toLowerCase().equals(colors[rdColor].toLowerCase()))
                {
                    loadText();
                    scoreCount += levelCount;
                    if(levelCount<10&&(scoreCount%50==0)) 
                    {
                        levelCount++;
                    }
                    timeCount =100;
                    time.start();
                }
                else {
                    time.stop();
                    mainLabel.setText("GAME OVER");
                    mainLabel.setForeground(Color.red);
                    oneBtn.setText("Color one");
                    twoBtn.setText("Color two");
                    desLabel.setText("Wrong Answer.");
                    startBtn.setText("Play again?");
                }
        }
    }//GEN-LAST:event_twoBtnActionPerformed
    public class loadTime implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            if(timeCount >0)
            {
                timeCount--;
                progressBar.setValue(timeCount);
            }
            else {
                mainLabel.setText("GAME OVER");
                mainLabel.setForeground(Color.red);
                oneBtn.setText("Color one");
                twoBtn.setText("Color two");
                desLabel.setText("Nice try.");
                startBtn.setText("Play again?");

            }
        }   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ktNhayBen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ktNhayBen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ktNhayBen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ktNhayBen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ktNhayBen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label desLabel;
    private javax.swing.JLabel levelLabel;
    private java.awt.Label mainLabel;
    private javax.swing.JButton oneBtn;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JButton startBtn;
    private javax.swing.JButton twoBtn;
    // End of variables declaration//GEN-END:variables
}
