/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaProject;

import java.math.BigInteger;
import javax.swing.*;

/**
 *
 * @author quyto
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form Demo
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jTabbedPane10 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane11 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        banKinh = new javax.swing.JTextField();
        tinh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dTich = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cVi = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        canhHv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dienTich = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        chuVi = new javax.swing.JTextField();
        tinhHv = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cRong = new javax.swing.JTextField();
        dTichHcn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cDai = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cViHcn = new javax.swing.JTextField();
        tinhHcn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane17 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        firstNumber = new javax.swing.JTextField();
        secondNumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ansTextArea = new javax.swing.JTextArea();
        signComboBox = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        base2Btn = new javax.swing.JLabel();
        base2TextField = new javax.swing.JTextField();
        base10TextField = new javax.swing.JTextField();
        base8TextField = new javax.swing.JTextField();
        base16TextField = new javax.swing.JTextField();
        base10Btn = new javax.swing.JLabel();
        base8Btn = new javax.swing.JLabel();
        base16Btn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ktTongHop = new javax.swing.JButton();
        ktHinhHocPhang = new javax.swing.JButton();
        ktSoHoc = new javax.swing.JButton();
        ktHinhHocKG = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        banKinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banKinhActionPerformed(evt);
            }
        });

        tinh.setText("Tính");
        tinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinhActionPerformed(evt);
            }
        });

        jLabel2.setText("Nhập bán kính:");

        jLabel7.setText("Chu vi");

        jLabel8.setText("Diện tích");

        cVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cViActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(dTich, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tinh, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(banKinh, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(185, 185, 185))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(230, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(cVi, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(285, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(banKinh, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(dTich, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(280, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(218, Short.MAX_VALUE)
                    .addComponent(cVi, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(84, 84, 84)))
        );

        jTabbedPane11.addTab("Hình Tròn", jPanel4);

        jLabel4.setText("Nhập cạnh");

        canhHv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canhHvActionPerformed(evt);
            }
        });

        jLabel5.setText("Chu vi");

        dienTich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dienTichActionPerformed(evt);
            }
        });

        jLabel6.setText("Diện tích");

        chuVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuViActionPerformed(evt);
            }
        });

        tinhHv.setText("Tính");
        tinhHv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinhHvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(tinhHv)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(canhHv)
                                .addComponent(jLabel5))
                            .addComponent(chuVi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(dienTich, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(canhHv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chuVi, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dienTich, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(tinhHv)
                .addGap(21, 21, 21))
        );

        jTabbedPane11.addTab("Hình Vuông", jPanel5);

        jLabel1.setText("Chiều dài ");

        jLabel3.setText("Chiều rộng");

        cRong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cRongActionPerformed(evt);
            }
        });

        dTichHcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dTichHcnActionPerformed(evt);
            }
        });

        jLabel9.setText("Chu vi");

        cDai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDaiActionPerformed(evt);
            }
        });

        jLabel10.setText("Diện tích");

        cViHcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cViHcnActionPerformed(evt);
            }
        });

        tinhHcn.setText("TÍnh");
        tinhHcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinhHcnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cDai, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cRong, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(cViHcn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(dTichHcn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(110, Short.MAX_VALUE))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(tinhHcn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cRong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cDai, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cViHcn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dTichHcn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(tinhHcn)
                .addContainerGap())
        );

        jTabbedPane11.addTab("Hình Chữ Nhật", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane11)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane11)
        );

        jTabbedPane10.addTab("Hình Học", jPanel1);

        firstNumber.setText("Số thứ nhất");
        firstNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNumberFocusLost(evt);
            }
        });
        firstNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNumberActionPerformed(evt);
            }
        });
        firstNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                firstNumberKeyReleased(evt);
            }
        });

        secondNumber.setText("Số thứ hai");
        secondNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                secondNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                secondNumberFocusLost(evt);
            }
        });
        secondNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                secondNumberKeyReleased(evt);
            }
        });

        ansTextArea.setColumns(20);
        ansTextArea.setLineWrap(true);
        ansTextArea.setRows(5);
        ansTextArea.setText("Kết quả\n");
        ansTextArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ansTextAreaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ansTextAreaFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(ansTextArea);

        signComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","+", "-", "x", "÷", "%" }));
        signComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(firstNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(secondNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jTabbedPane17.addTab("Tính toán", jPanel11);

        base2Btn.setText("Cơ số 2");

        base2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                base2TextFieldActionPerformed(evt);
            }
        });
        base2TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                base2TextFieldKeyReleased(evt);
            }
        });

        base10TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                base10TextFieldKeyReleased(evt);
            }
        });

        base8TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                base8TextFieldKeyReleased(evt);
            }
        });

        base16TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                base16TextFieldKeyReleased(evt);
            }
        });

        base10Btn.setText("Cơ số 10");

        base8Btn.setText("Cơ số 8");

        base16Btn.setText("Cơ số 16");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(base2Btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(base10Btn)
                            .addComponent(base8Btn)
                            .addComponent(base16Btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(base16TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(base2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(base10TextField)
                            .addComponent(base8TextField))))
                .addGap(61, 61, 61))
        );

        jPanel12Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {base10TextField, base16TextField, base2TextField, base8TextField});

        jPanel12Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {base10Btn, base16Btn, base2Btn, base8Btn});

        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(base2Btn)
                    .addComponent(base2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(base10Btn)
                    .addComponent(base10TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(base8Btn)
                    .addComponent(base8TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(base16Btn)
                    .addComponent(base16TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel12Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {base10TextField, base16TextField, base2TextField, base8TextField});

        jPanel12Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {base10Btn, base16Btn, base2Btn, base8Btn});

        jTabbedPane17.addTab("Chuyển đổi cơ số", jPanel12);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane17)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane17)
        );

        jTabbedPane10.addTab("Số Học", jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(343, 343));

        ktTongHop.setText("Luyện trí nhớ");
        ktTongHop.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ktTongHopComponentShown(evt);
            }
        });
        ktTongHop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ktTongHopActionPerformed(evt);
            }
        });

        ktHinhHocPhang.setText("Hình Học Phẳng");
        ktHinhHocPhang.setMaximumSize(new java.awt.Dimension(151, 25));
        ktHinhHocPhang.setMinimumSize(new java.awt.Dimension(151, 25));
        ktHinhHocPhang.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ktHinhHocPhangComponentShown(evt);
            }
        });
        ktHinhHocPhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ktHinhHocPhangActionPerformed(evt);
            }
        });

        ktSoHoc.setText("Số học");
        ktSoHoc.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ktSoHocComponentShown(evt);
            }
        });
        ktSoHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ktSoHocActionPerformed(evt);
            }
        });

        ktHinhHocKG.setText("Hình học không gian ");
        ktHinhHocKG.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ktHinhHocKGComponentShown(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ktSoHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(ktHinhHocPhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ktHinhHocKG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ktTongHop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ktHinhHocKG, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(ktHinhHocPhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ktSoHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ktTongHop, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane10.addTab("Kiểm tra", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane10)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane10)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void ktTongHopComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ktTongHopComponentShown
       
      
    }//GEN-LAST:event_ktTongHopComponentShown

    private void ktHinhHocPhangComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ktHinhHocPhangComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_ktHinhHocPhangComponentShown

    private void ktSoHocComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ktSoHocComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_ktSoHocComponentShown

    private void ktHinhHocKGComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ktHinhHocKGComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_ktHinhHocKGComponentShown

    private void ktHinhHocPhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ktHinhHocPhangActionPerformed
        if(evt.getSource()== ktHinhHocPhang ) {  
//            ktHHP k= new ktHHP();
//            k.setVisible(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_ktHinhHocPhangActionPerformed


    private void ktTongHopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ktTongHopActionPerformed
      
      BrainTranning a= new BrainTranning();
      a.setVisible(true);

    }//GEN-LAST:event_ktTongHopActionPerformed
   private void ktSoHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ktSoHocActionPerformed
       if(evt.getSource()== ktSoHoc){
           ktSoHoc k= new ktSoHoc();
           k.setVisible(true);
       }
    }//GEN-LAST:event_ktSoHocActionPerformed
// fix conflict


    public static String baseConvert(String n,int src,int dest){
        return Integer.toString(Integer.parseInt(n, src),dest); 
    }
    
    public void setBaseTextField(JTextField j,int base){
        base2TextField.setText(baseConvert(j.getText(),base,2));
        base10TextField.setText(baseConvert(j.getText(),base,10));
        base8TextField.setText(baseConvert(j.getText(),base,8));
        base16TextField.setText(baseConvert(j.getText(),base,16));
    }
    
    public void processTextFieldConvert(JTextField j,int base){
        try{
            switch(base){
                case 2:
                    setBaseTextField(j,2);
                    break;
                case 10:
                    setBaseTextField(j,10);
                    break;
                case 8:
                    setBaseTextField(j,8);
                    break;
                case 16:
                    setBaseTextField(j,16);
                    break;
            }
        }
        catch(NumberFormatException e){
            
        }
        
    }
    
    public void setTextFieldNull(){
        base2TextField.setText("");
        base10TextField.setText("");
        base8TextField.setText("");
        base16TextField.setText("");
    }
    
    private void base2TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_base2TextFieldKeyReleased
        if(base2TextField.getText().equals("")){
            setTextFieldNull();
        }
        else{
            processTextFieldConvert(base2TextField,2);
        }
    }//GEN-LAST:event_base2TextFieldKeyReleased

    private void base10TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_base10TextFieldKeyReleased
        if(base10TextField.getText().equals("")){
            setTextFieldNull();
        }
        else{
            processTextFieldConvert(base10TextField,10);
        }
        
    }//GEN-LAST:event_base10TextFieldKeyReleased

    private void base8TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_base8TextFieldKeyReleased
        if(base8TextField.getText().equals("")){
            setTextFieldNull();
        }
        else{
            processTextFieldConvert(base8TextField,8);
        }
        
    }//GEN-LAST:event_base8TextFieldKeyReleased

    private void base16TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_base16TextFieldKeyReleased
        if(base16TextField.getText().equals("")){
            setTextFieldNull();
        }
        else{
            processTextFieldConvert(base16TextField,16);
        }
    }//GEN-LAST:event_base16TextFieldKeyReleased

    private void firstNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNumberFocusGained
        if (firstNumber.getText().equals("Số thứ nhất")) {
            firstNumber.setText("");
        }
    }//GEN-LAST:event_firstNumberFocusGained

    private void firstNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNumberFocusLost
        if (firstNumber.getText().isEmpty()) {
            firstNumber.setText("Số thứ nhất");
        }
    }//GEN-LAST:event_firstNumberFocusLost

    private void secondNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_secondNumberFocusGained
        if (secondNumber.getText().equals("Số thứ hai")) {
            secondNumber.setText("");
        }
    }//GEN-LAST:event_secondNumberFocusGained

    private void secondNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_secondNumberFocusLost
        if (secondNumber.getText().isEmpty()) {
            secondNumber.setText("Số thứ hai");
        }
    }//GEN-LAST:event_secondNumberFocusLost

    public void calc(){
        try{
            BigInteger a = new BigInteger(firstNumber.getText());
            BigInteger b = new BigInteger(secondNumber.getText());
            switch(signComboBox.getSelectedItem().toString()){
                case "+":
                    ansTextArea.setText(a.add(b).toString());
                    break;
                case "-":
                    ansTextArea.setText(a.subtract(b).toString());
                    break;
                case "x":
                    ansTextArea.setText(a.multiply(b).toString());
                    break;
                case "÷":
                    ansTextArea.setText(a.divide(b).toString());
                    break;
                case "%":
                    ansTextArea.setText(a.mod(b).toString());
                    break;
                default:
                    ansTextArea.setText("");
                    break;
            }
        }
        catch(NumberFormatException e){
            
        }
    }
    
    private void firstNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNumberKeyReleased
        calc();
    }//GEN-LAST:event_firstNumberKeyReleased

    private void secondNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secondNumberKeyReleased
        calc();
    }//GEN-LAST:event_secondNumberKeyReleased

    private void signComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signComboBoxActionPerformed
        calc();
    }//GEN-LAST:event_signComboBoxActionPerformed

    private void ansTextAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ansTextAreaFocusGained
        if (firstNumber.getText().equals("Kết quả")) {
            firstNumber.setText("");
        }
    }//GEN-LAST:event_ansTextAreaFocusGained

    private void ansTextAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ansTextAreaFocusLost
        if (firstNumber.getText().isEmpty()) {
            firstNumber.setText("Kết quả");
        }
    }//GEN-LAST:event_ansTextAreaFocusLost

    private void base2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_base2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_base2TextFieldActionPerformed

    private void canhHvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canhHvActionPerformed
        
    }//GEN-LAST:event_canhHvActionPerformed

    private void dienTichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dienTichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dienTichActionPerformed

    private void chuViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuViActionPerformed
         
         
         
    }//GEN-LAST:event_chuViActionPerformed

    private void firstNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNumberActionPerformed

    private void tinhHvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinhHvActionPerformed
       double a= Double.parseDouble(canhHv.getText());
         if(evt.getSource()==tinhHv) chuVi.setText(String.valueOf(a*4)); dienTich.setText(String.valueOf(a*a));
    }//GEN-LAST:event_tinhHvActionPerformed

    private void tinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinhActionPerformed
        double x= Double.parseDouble(banKinh.getText());
        double dt=0;
        double cv=0;

        if(evt.getSource()==tinh){
            dt= x * x *3.14;
            cv= (Math.round(2* 3.14 *x*10)/10);
        }
        cVi.setText(String.valueOf(cv));
        dTich.setText(String.valueOf(dt));
    }//GEN-LAST:event_tinhActionPerformed

    private void banKinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banKinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_banKinhActionPerformed

    private void cViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cViActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cViActionPerformed

    private void dTichHcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dTichHcnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dTichHcnActionPerformed

    private void cRongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cRongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cRongActionPerformed

    private void cDaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cDaiActionPerformed

    private void cViHcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cViHcnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cViHcnActionPerformed

    private void tinhHcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinhHcnActionPerformed
         double a= Double.parseDouble(cDai.getText());
         double b= Double.parseDouble(cRong.getText());
         
         if(evt.getSource()== tinhHcn){
             cViHcn.setText(String.valueOf(a*2+b*2));
             dTichHcn.setText(String.valueOf(a*b));
         }
         
    }//GEN-LAST:event_tinhHcnActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ansTextArea;
    private javax.swing.JTextField banKinh;
    private javax.swing.JLabel base10Btn;
    private javax.swing.JTextField base10TextField;
    private javax.swing.JLabel base16Btn;
    private javax.swing.JTextField base16TextField;
    private javax.swing.JLabel base2Btn;
    private javax.swing.JTextField base2TextField;
    private javax.swing.JLabel base8Btn;
    private javax.swing.JTextField base8TextField;
    private javax.swing.JTextField cDai;
    private javax.swing.JTextField cRong;
    private javax.swing.JTextField cVi;
    private javax.swing.JTextField cViHcn;
    private javax.swing.JTextField canhHv;
    private javax.swing.JTextField chuVi;
    private javax.swing.JTextField dTich;
    private javax.swing.JTextField dTichHcn;
    private javax.swing.JTextField dienTich;
    private javax.swing.JTextField firstNumber;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane10;
    private javax.swing.JTabbedPane jTabbedPane11;
    private javax.swing.JTabbedPane jTabbedPane17;
    private javax.swing.JButton ktHinhHocKG;
    private javax.swing.JButton ktHinhHocPhang;
    private javax.swing.JButton ktSoHoc;
    private javax.swing.JButton ktTongHop;
    private javax.swing.JTextField secondNumber;
    private javax.swing.JComboBox<String> signComboBox;
    private javax.swing.JButton tinh;
    private javax.swing.JButton tinhHcn;
    private javax.swing.JButton tinhHv;
    // End of variables declaration//GEN-END:variables
}
